# Generated by Django 4.0.6 on 2022-07-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=35, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=35, verbose_name='Username')),
                ('Acc_Num', models.CharField(max_length=10, verbose_name='Account Number')),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
    ]
