# Generated by Django 4.0.6 on 2022-09-21 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=35, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=35, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='pin',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=35, verbose_name='Username'),
        ),
    ]
