# Generated by Django 4.0.6 on 2022-07-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
