# Generated by Django 4.0.6 on 2022-10-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0005_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=4),
        ),
    ]
